POST http://127.0.0.1:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJub25lIn0.eyJzdWIiOiJteS11c2VyIiwibmJmIjoxNjY4MzM5NDQ1LCJyb2xlcyI6W10sImlzcyI6ImZsaWdodHMiLCJleHAiOjE2NjgzNDMwNDUsImlhdCI6MTY2ODMzOTQ0NX0.

{
  "flightId": 3,
  "firstName": "Maciej",
  "lastName": "Zielinski",
  "passportNumber": "123-523-1252"
}