POST http://127.0.0.1:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJub25lIn0.eyJzdWIiOiJteS11c2VyIiwibmJmIjoxNjY4MzQ4MDEyLCJyb2xlcyI6W10sImlzcyI6ImZsaWdodHMiLCJleHAiOjE2NjgzNTE2MTIsImlhdCI6MTY2ODM0ODAxMn0.

{
  "flightId": 3,
  "firstName": "Maciej",
  "lastName": "Zielinski",
  "passportNumber": "123-523-1252"
}