POST http://127.0.0.1:8080/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJub25lIn0.eyJzdWIiOiJteS11c2VyIiwibmJmIjoxNjY4MDg2ODI4LCJyb2xlcyI6W10sImlzcyI6ImZsaWdodHMiLCJleHAiOjE2NjgwOTA0MjgsImlhdCI6MTY2ODA4NjgyOH0.

{
  "flightId": 3,
  "firstName": "Maciej",
  "lastName": "Zielinski",
  "passportNumber": "123-523-1252"
}