micronaut:
  application:
    name: flights
  security:
    enabled: true
    authentication: bearer
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        signature:
          secret:
            generator:
              secret: change-it-and-has-to-have-proper-length
              jws-algorithm: HS256

datasources:
  default:
    url: ${PG_JDBC_URL:`jdbc:postgresql://127.0.0.1:5432/ldi-flight-booker`}
    username: ${PG_USERNAME:postgres}
    password: ${PG_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
    schema-generator: NONE
    dialect: POSTGRES

jpa:
  default:
    reactive: false
    entity-scan:
      packages:
        - com.maciezie.ldi.flights.domain
        - com.maciezie.ldi.reservations.domain
    properties:
      hibernate:
        show_sql: false

netty:
  default:
    allocator:
      max-order: 3

# validate | update | create | create-drop | none
jpa.default.properties.hibernate.hbm2ddl.auto: create

jackson:
  deserialization:
    failOnUnknownProperties: false
  date-format: yyyy-MM-dd HH:mm:ss

kafka:
  bootstrap:
    servers: localhost:9092
