version: '3.7'

services:
  flight-booker:
    image: flights:latest
    networks:
      hostnet: {}
    environment:
      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  hostnet:
    external: true
    name: host

